title: Sahil Singh
email: sahil95@live.ca
description: SAHIL WAS HERE
baseurl: "" 
url: "https://sahil-s-lab.github.io/portfolio/" 

theme: null

# site settings
taglong: Data Analyst with a strategic mindset and a passion for turning complexity into clarity
tagshort: Data Analyst
cv: true

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/img/headshot2.jpg
address: Foobar Hall 1.23
phone: +1 647 783 1123

# profile links
profile:
  linkedin: https://linkedin.com/in/sahil95

# build settings
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  #style: compressed
  sourcemap: never
  
