title: Sahil Singh
email: sahil95@live.ca
description: SAHIL WAS HERE
baseurl: "" 
url: "https://sahil-s-lab.github.io/portfolio/" 

theme: cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
cv: true

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# profile links
profile:
  linkedin: https://linkedin.com/in/sahil95

# build settings
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  #style: compressed
  sourcemap: never
  
