title: Sahil Singh
email: sahil95@live.ca
description: >-
  Brief description about you or the portfolio.
baseurl: "" # Leave this empty unless you're using a project page
url: "https://sahil-s-lab.github.io/portfolio/" 

markdown: kramdown
theme: null  # IMPORTANT: Do not use a built-in theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty
