title: Sahil Singh, MMA
email: sahil95@live.ca
description: Sahil Singh's professional portfolio presents data analytics projects across business intelligence, sales optimization, and predictive modeling. 
baseurl: "" 
url: "https://sahil-s-lab.github.io/portfolio/" 

theme: null

# site settings
taglong: Data Analyst with a strategic mindset and a passion for turning complexity into clarity
tagshort: ""
cv: true

# author settings
author:
  name: Place Holder
  email: sahil95@live.ca
photo: assets/img/headshot3.jpg
address: Place Holder
phone: +1 647 783 1123

# profile links
profile:
  linkedin: https://linkedin.com/in/sahil95
  github: https://github.com/sahil-s-lab/portfolio/tree/main

# build settings
permalink: pretty

include:
  - "**/*.sql"
  
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never
  
